version: '2.3'

services:
  main:
    container_name: landmark
    build:
      context: ./
      dockerfile: Dockerfile
    runtime: nvidia
    restart: always
    volumes:
      - type: volume
        source: nfs_shared
        target: /mldisk/nfs_shared
        volume:
          nocopy: true
      - type: volume
        source: nfs_shared_
        target: /mldisk/nfs_shared_
        volume:
          nocopy: true
      - "/media/mmlab/hdd:/hdd"
    ports:
      - "{host ssh}:22"
      - "{host tensorboard}:6006"
    ipc: host
    stdin_open: true
    tty: true

volumes:
  nfs_shared:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk2.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume2/nfs_shared"
  nfs_shared_:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk2.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume3/nfs_shared_"